In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [5]:
df_br = pd.read_csv('campeonato-brasileiro-estatisticas-full.csv')
df_br.tail()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
17565,8776,38,Fortaleza,0,0,NaN,0,NaN,0,0,0,0,0
17566,8780,38,Criciuma,0,0,NaN,0,NaN,0,0,0,0,0
17567,8780,38,Bragantino,0,0,NaN,0,NaN,0,0,0,0,0
17568,8785,38,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
17569,8785,38,Corinthians,0,0,NaN,0,NaN,0,0,0,0,0

In [6]:
df_br = df_br.fillna('Não informado')
df_br.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,Não informado,0,Não informado,0,0,0,0,0
1,1,1,Guarani,0,0,Não informado,0,Não informado,0,0,0,0,0
2,2,1,Athletico-PR,0,0,Não informado,0,Não informado,0,0,0,0,0
3,2,1,Gremio,0,0,Não informado,0,Não informado,0,0,0,0,0
4,3,1,Flamengo,0,0,Não informado,0,Não informado,0,0,0,0,0

In [7]:
df_br['posse_de_bola'].unique()

array(['Não informado', '35%', '65%', '56%', '44%', '57%', '43%', '58%',
       '42%', '52%', '48%', '39%', '61%', '46%', '54%', '53%', '47%',
       '67%', '33%', '51%', '49%', '55%', '45%', '50%', '26%', '74%',
       '62%', '38%', '41%', '59%', '60%', '40%', '63%', '37%', '36%',
       '64%', '68%', '32%', '30%', '70%', '34%', '66%', '69%', '31%',
       '23%', '77%', '27%', '73%', '78%', '22%', '76%', '24%', '28%',
       '72%', '71%', '29%', '75%', '25%', '79%', '21%', '20%', '80%'],
      dtype=object)

In [8]:
df_br[df_br['partida_id'] == 5358]

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
10714,5358,38,Flamengo,15,0,65%,559,Não informado,16,0,0,1,1
10715,5358,38,Palmeiras,14,0,35%,304,Não informado,20,1,0,4,5

In [9]:
df_br = df_br.sort_values(by='partida_id', ascending=True)
df_br.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,Não informado,0,Não informado,0,0,0,0,0
1,1,1,Guarani,0,0,Não informado,0,Não informado,0,0,0,0,0
2,2,1,Athletico-PR,0,0,Não informado,0,Não informado,0,0,0,0,0
3,2,1,Gremio,0,0,Não informado,0,Não informado,0,0,0,0,0
4,3,1,Flamengo,0,0,Não informado,0,Não informado,0,0,0,0,0

In [10]:
colunas_verificacao = [
    'chutes', 'chutes_no_alvo', 'posse_de_bola', 'passes',
    'precisao_passes', 'faltas', 'cartao_amarelo', 'cartao_vermelho',
    'impedimentos', 'escanteios'
]

In [11]:
df_br['type'] = df_br[colunas_verificacao].apply(
    lambda row: 0 if all((row == 0) | (row == 'Não informado')) else 1, axis=1
)

In [12]:
df_validos = df_br[df_br['type'] == 1]
df_invalidos = df_br[df_br['type'] == 0]
df_invalidos.head(100)

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,type
0,1,1,Vasco,0,0,Não informado,0,Não informado,0,0,0,0,0,0
1,1,1,Guarani,0,0,Não informado,0,Não informado,0,0,0,0,0,0
2,2,1,Athletico-PR,0,0,Não informado,0,Não informado,0,0,0,0,0,0
3,2,1,Gremio,0,0,Não informado,0,Não informado,0,0,0,0,0,0
4,3,1,Flamengo,0,0,Não informado,0,Não informado,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,48,3,Fluminense,0,0,Não informado,0,Não informado,0,0,0,0,0,0
98,49,5,Bahia,0,0,Não informado,0,Não informado,0,0,0,0,0,0
99,49,5,Atletico-MG,0,0,Não informado,0,Não informado,0,0,0,0,0,0
100,50,5,Sao Caetano,0,0,Não informado,0,Não informado,0,0,0,0,0,0
101,50,5,Gremio,0,0,Não informado,0,Não informado,0,0,0,0,0,0

In [13]:
df_br['clube'].value_counts()

clube
Flamengo           856
Fluminense         856
Sao Paulo          856
Athletico-PR       818
Internacional      818
Corinthians        818
Santos             818
Atletico-MG        817
Gremio             776
Palmeiras          772
Cruzeiro           742
Botafogo-RJ        734
Vasco              666
Coritiba           590
Goias              590
Bahia              464
Figueirense        438
Vitoria            434
Sport              418
Ponte Preta        362
Fortaleza          354
Juventude          324
Atletico-GO        304
Ceara              266
Avai               266
Chapecoense        265
Parana             248
America-MG         228
Criciuma           206
Bragantino         190
Nautico            190
Sao Caetano        172
Cuiaba             152
Paysandu           134
Guarani            130
Portuguesa         114
Santa Cruz          76
Brasiliense         42
Barueri             38
America-RN          38
Ipatinga            38
Santo Andre         38
Gremio Prudente     38
CSA                 38
Joinville           38
Name: count, dtype: int64

In [20]:
df_media = df_br.groupby('clube').mean(numeric_only=True).reset_index()
num_cols = df_media.select_dtypes(include=[np.number]).columns

df_media[num_cols] = df_media[num_cols].applymap(lambda x: np.floor(x + 0.5))
df_media

C:\Users\elias\AppData\Local\Temp\ipykernel_8484\2919866356.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_media[num_cols] = df_media[num_cols].applymap(lambda x: np.floor(x + 0.5))

,clube,partida_id,rodata,chutes,chutes_no_alvo,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,type
0,America-MG,6506.0,20.0,11.0,3.0,320.0,12.0,2.0,0.0,1.0,4.0,1.0
1,America-RN,2136.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Athletico-PR,4511.0,20.0,5.0,1.0,171.0,6.0,1.0,0.0,1.0,2.0,0.0
3,Atletico-GO,5984.0,20.0,6.0,2.0,197.0,8.0,1.0,0.0,1.0,3.0,1.0
4,Atletico-MG,4616.0,20.0,6.0,2.0,201.0,6.0,1.0,0.0,1.0,2.0,0.0
5,Avai,5068.0,20.0,7.0,1.0,211.0,8.0,1.0,0.0,1.0,3.0,1.0
6,Bahia,5530.0,20.0,7.0,2.0,197.0,8.0,1.0,0.0,1.0,3.0,0.0
7,Barueri,2896.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Botafogo-RJ,4566.0,20.0,5.0,1.0,146.0,5.0,1.0,0.0,1.0,2.0,0.0
9,Bragantino,7835.0,20.0,12.0,4.0,337.0,12.0,2.0,0.0,1.0,5.0,1.0
10,Brasiliense,1335.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,CSA,6697.0,20.0,10.0,3.0,315.0,14.0,2.0,0.0,2.0,3.0,1.0
12,Ceara,6044.0,20.0,9.0,3.0,268.0,11.0,2.0,0.0,1.0,4.0,1.0
13,Chapecoense,5992.0,19.0,10.0,2.0,309.0,14.0,2.0,0.0,1.0,4.0,1.0
14,Corinthians,4582.0,20.0,5.0,1.0,202.0,5.0,1.0,0.0,1.0,2.0,0.0
15,Coritiba,4182.0,20.0,5.0,1.0,149.0,6.0,1.0,0.0,1.0,2.0,0.0
16,Criciuma,3532.0,21.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0
17,Cruzeiro,4035.0,20.0,4.0,1.0,136.0,4.0,1.0,0.0,1.0,2.0,0.0
18,Cuiaba,8026.0,20.0,9.0,3.0,283.0,10.0,2.0,0.0,1.0,4.0,1.0
19,Figueirense,2815.0,21.0,2.0,0.0,58.0,3.0,0.0,0.0,0.0,1.0,0.0
20,Flamengo,4491.0,20.0,6.0,2.0,197.0,6.0,1.0,0.0,1.0,2.0,0.0
21,Fluminense,4491.0,20.0,5.0,1.0,183.0,6.0,1.0,0.0,1.0,2.0,0.0
22,Fortaleza,5307.0,20.0,7.0,2.0,206.0,8.0,1.0,0.0,1.0,2.0,1.0
23,Goias,3839.0,20.0,4.0,1.0,109.0,5.0,1.0,0.0,1.0,1.0,0.0
24,Gremio,4498.0,20.0,5.0,1.0,191.0,6.0,1.0,0.0,1.0,2.0,0.0
25,Gremio Prudente,3276.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Guarani,1349.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,Internacional,4424.0,20.0,5.0,1.0,162.0,6.0,1.0,0.0,1.0,2.0,0.0
28,Ipatinga,2516.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,Joinville,5176.0,20.0,11.0,0.0,350.0,17.0,2.0,0.0,2.0,5.0,1.0
30,Juventude,3588.0,21.0,3.0,1.0,89.0,3.0,1.0,0.0,0.0,1.0,0.0
31,Nautico,3200.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,Palmeiras,4746.0,20.0,7.0,2.0,187.0,7.0,1.0,0.0,1.0,3.0,0.0
33,Parana,1995.0,21.0,2.0,0.0,53.0,2.0,0.0,0.0,0.0,1.0,0.0
34,Paysandu,798.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,Ponte Preta,3117.0,21.0,4.0,0.0,120.0,5.0,1.0,0.0,1.0,2.0,0.0
36,Portuguesa,3656.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,Santa Cruz,3656.0,20.0,6.0,0.0,203.0,8.0,1.0,0.0,1.0,3.0,1.0
38,Santo Andre,2896.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,Santos,4300.0,20.0,5.0,1.0,180.0,6.0,1.0,0.0,1.0,2.0,0.0
40,Sao Caetano,1009.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,Sao Paulo,4491.0,20.0,5.0,1.0,185.0,6.0,1.0,0.0,1.0,2.0,0.0
42,Sport,4900.0,20.0,6.0,1.0,225.0,8.0,1.0,0.0,1.0,3.0,1.0
43,Vasco,4144.0,20.0,4.0,1.0,134.0,5.0,1.0,0.0,1.0,2.0,0.0
44,Vitoria,3996.0,20.0,4.0,1.0,100.0,5.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
# dicionário com médias por clube
medias_dict = df_media.set_index('clube').to_dict(orient='index')

# aplica substituição somente onde type == 0
for idx, row in df_br[df_br['type'] == 0].iterrows():
    clube = row['clube']
    if clube in medias_dict:
        for col in df_media.columns:
            if col != 'clube':  # não substituir nome do time
                df_br.at[idx, col] = medias_dict[clube][col]

In [25]:
df_br[df_br['type'] == 0]

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,type
0,4144,20,Vasco,4,1,Não informado,134,Não informado,5,1,0,1,2,0
1,1349,22,Guarani,0,0,Não informado,0,Não informado,0,0,0,0,0,0
2,4511,20,Athletico-PR,5,1,Não informado,171,Não informado,6,1,0,1,2,0
3,4498,20,Gremio,5,1,Não informado,191,Não informado,6,1,0,1,2,0
4,4491,20,Flamengo,6,2,Não informado,197,Não informado,6,1,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17561,4144,20,Vasco,4,1,Não informado,134,Não informado,5,1,0,1,2,0
17562,4491,20,Fluminense,5,1,Não informado,183,Não informado,6,1,0,1,2,0
17563,4746,20,Palmeiras,7,2,Não informado,187,Não informado,7,1,0,1,3,0
17569,4582,20,Corinthians,5,1,Não informado,202,Não informado,5,1,0,1,2,0
17568,4498,20,Gremio,5,1,Não informado,191,Não informado,6,1,0,1,2,0